version: "3.8"

x-logging:
  &default-logging
  logging:
    driver: json-file

x-php:
  &default-php
  restart: "no"
  volumes:
    - ./bin:/app/bin:cached
    - ./config:/app/config:cached
    - ./src:/app/src:cached
    - ./docker:/app/docker:cached
  env_file:
    - .env
  environment:
    # - APP_SECRET=${APP_SECRET:?You need to set the APP_SECRET environment variable}
    # - APP_RELEASE=${APP_RELEASE:?You need to set the APP_RELEASE environment variable}
    - APP_SECRET
    - APP_RELEASE
  depends_on:
    - postgres
    - memcached
    - redis
    - rabbitmq

volumes:
  rabbitmq: {}
  postgres: {}

# https://github.com/docker/compose/issues/4675
services:
  nginx:
    image: soprun/sandbox-nginx:latest
    hostname: nginx
    container_name: nginx
    depends_on:
      - php
    ports:
      - 80:80
      - 443:443

  php:
    image: soprun/sandbox-php:latest
    hostname: php
    container_name: php
    privileged: true
    <<: *default-php
    <<: *default-logging
    ports:
      - 9000

  php_cli:
    image: soprun/sandbox-php-cli:latest
    hostname: php_cli
    container_name: php_cli
    tty: true
    <<: *default-php

  postgres:
    image: postgres:latest
    hostname: postgres
    container_name: postgres
    restart: on-failure
    <<: *default-logging
    ports:
      - 5432
    volumes:
      - ./docker/postgres/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - postgres:/var/lib/postgresql/data
    environment:
      # - PGDATA: /var/lib/postgresql/data/pgdata
      - POSTGRES_DB
      - POSTGRES_USERNAME
      - POSTGRES_PASSWORD
      - POSTGRES_HOST_AUTH_METHOD

  rabbitmq:
    image: rabbitmq:3.8.5-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    restart: on-failure
    <<: *default-logging
    ports:
      - 5672:5672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST}

  rabbitmq-management:
    image: rabbitmq:3.8.5-management-alpine
    container_name: rabbitmq-management
    restart: always
    ports:
      - 15672:15672

  memcached:
    image: memcached:latest
    container_name: memcached
    hostname: memcached
    restart: always
    ports:
      - 11211:11211

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
