monolog:
  handlers:
    main:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
      channels: ["!event"]

    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine", "!console"]

    stdout:
      type: stream
      path: 'php://stdout'
      level: info
      channels: ['!event', '!doctrine', '!php', '!security']
      # formatter: monolog.formatter.json

#    stderr:
#      type: stream
#      path: 'php://stderr'
#      level: error
#      channels: ['!event']
#      # formatter: monolog.formatter.json
