###
### Docker default Logging config
###

LOGGING_DRIVER=json-file
LOGGING_OPTIONS_MAX_SIZE=200k
LOGGING_OPTIONS_MAX_FILE=10

###
### Docker default Network config
###

NETWORK_NAME="${APP_NAMESPACE}-network"
# If you want to customize the created network, use the following variable
NETWORK_OPTIONS="--driver=bridge"
# Set the IP address of the external access interface
NETWORK_IP=0.0.0.0
# Set the local exposed ports for http and https on the Host
NETWORK_HTTP=80
NETWORK_HTTPS=443
NETWORK_HTTPS_ENABLE=1
NETWORK_HTTPS_REDIRECT=1