name: Docker Image CI

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  VERSION: latest

  IMAGE_NGINX_NAME: soprun/sandbox-nginx
  IMAGE_NGINX_FILE: ./docker/nginx/Dockerfile

  IMAGE_PHP_NAME: soprun/sandbox-php
  IMAGE_PHP_FILE: ./docker/php/Dockerfile

  IMAGE_PHP_CLI_NAME: soprun/sandbox-php-cli
  IMAGE_PHP_CLI_FILE: ./docker/php-cli/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Version detection
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          # see: https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
          # echo "::set-env name=action_state::yellow"

      - name: Build Nginx
        run: docker build \
          --build-arg APP_ENV=dev \
          --build-arg APP_DEBUG=1 \
          --file ${{ env.IMAGE_NGINX_FILE }} \
          --tag "${{ env.IMAGE_NGINX_NAME }}:${{ env.VERSION }}" \
          .

      - name: Build PHP-FPM
        run: docker build \
          --build-arg APP_ENV=dev \
          --build-arg APP_DEBUG=1 \
          --file ${{ env.IMAGE_PHP_FILE }} \
          --tag "${{ env.IMAGE_PHP_NAME }}:${{ env.VERSION }}" \
          .

      - name: Build PHP-CLI
        run: docker build \
          --build-arg APP_ENV=dev \
          --build-arg APP_DEBUG=1 \
          --file ${{ env.IMAGE_PHP_CLI_FILE }} \
          --tag "${{ env.IMAGE_PHP_CLI_NAME }}:${{ env.VERSION }}" \
          .

      - name: Pushe the Docker image
        run: |
          docker push ${{ env.IMAGE_NGINX_NAME }}
          docker push ${{ env.IMAGE_PHP_NAME }}
          docker push ${{ env.IMAGE_PHP_CLI_NAME }}
